package com.yanbin.dao.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ba_user.id
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ba_user.tenant_id
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ba_user.code
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ba_user.name
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ba_user.status_id
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    private Integer statusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ba_user.mobile
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ba_user.email
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ba_user.icon_path
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    private String iconPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ba_user.session
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    private String session;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ba_user.login_date
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    private Date loginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ba_user.login_client_type_id
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    private Integer loginClientTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ba_user.login_client
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    private String loginClient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ba_user.note
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ba_user.password
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ba_user.failed_logins
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    private Integer failedLogins;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ba_user.password_expired_date
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    private Date passwordExpiredDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ba_user.id
     *
     * @return the value of ba_user.id
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ba_user.id
     *
     * @param id the value for ba_user.id
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ba_user.tenant_id
     *
     * @return the value of ba_user.tenant_id
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ba_user.tenant_id
     *
     * @param tenantId the value for ba_user.tenant_id
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ba_user.code
     *
     * @return the value of ba_user.code
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ba_user.code
     *
     * @param code the value for ba_user.code
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ba_user.name
     *
     * @return the value of ba_user.name
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ba_user.name
     *
     * @param name the value for ba_user.name
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ba_user.status_id
     *
     * @return the value of ba_user.status_id
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ba_user.status_id
     *
     * @param statusId the value for ba_user.status_id
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ba_user.mobile
     *
     * @return the value of ba_user.mobile
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ba_user.mobile
     *
     * @param mobile the value for ba_user.mobile
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ba_user.email
     *
     * @return the value of ba_user.email
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ba_user.email
     *
     * @param email the value for ba_user.email
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ba_user.icon_path
     *
     * @return the value of ba_user.icon_path
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public String getIconPath() {
        return iconPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ba_user.icon_path
     *
     * @param iconPath the value for ba_user.icon_path
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public void setIconPath(String iconPath) {
        this.iconPath = iconPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ba_user.session
     *
     * @return the value of ba_user.session
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public String getSession() {
        return session;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ba_user.session
     *
     * @param session the value for ba_user.session
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public void setSession(String session) {
        this.session = session;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ba_user.login_date
     *
     * @return the value of ba_user.login_date
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public Date getLoginDate() {
        return loginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ba_user.login_date
     *
     * @param loginDate the value for ba_user.login_date
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public void setLoginDate(Date loginDate) {
        this.loginDate = loginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ba_user.login_client_type_id
     *
     * @return the value of ba_user.login_client_type_id
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public Integer getLoginClientTypeId() {
        return loginClientTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ba_user.login_client_type_id
     *
     * @param loginClientTypeId the value for ba_user.login_client_type_id
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public void setLoginClientTypeId(Integer loginClientTypeId) {
        this.loginClientTypeId = loginClientTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ba_user.login_client
     *
     * @return the value of ba_user.login_client
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public String getLoginClient() {
        return loginClient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ba_user.login_client
     *
     * @param loginClient the value for ba_user.login_client
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public void setLoginClient(String loginClient) {
        this.loginClient = loginClient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ba_user.note
     *
     * @return the value of ba_user.note
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ba_user.note
     *
     * @param note the value for ba_user.note
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ba_user.password
     *
     * @return the value of ba_user.password
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ba_user.password
     *
     * @param password the value for ba_user.password
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ba_user.failed_logins
     *
     * @return the value of ba_user.failed_logins
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public Integer getFailedLogins() {
        return failedLogins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ba_user.failed_logins
     *
     * @param failedLogins the value for ba_user.failed_logins
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public void setFailedLogins(Integer failedLogins) {
        this.failedLogins = failedLogins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ba_user.password_expired_date
     *
     * @return the value of ba_user.password_expired_date
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public Date getPasswordExpiredDate() {
        return passwordExpiredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ba_user.password_expired_date
     *
     * @param passwordExpiredDate the value for ba_user.password_expired_date
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    public void setPasswordExpiredDate(Date passwordExpiredDate) {
        this.passwordExpiredDate = passwordExpiredDate;
    }
}