package com.yanbin.dao;

import com.yanbin.dao.model.User;
import com.yanbin.dao.model.UserExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ba_user
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ba_user
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ba_user
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ba_user
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ba_user
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ba_user
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ba_user
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ba_user
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ba_user
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ba_user
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ba_user
     *
     * @mbggenerated Mon Jul 03 17:26:18 CST 2017
     */
    int updateByPrimaryKey(User record);
}